import React from "react";
import "./HomeSection.css";


const cards = [
  {
    title: "National Reach, Local Luxury",
    description:
      "Access the most prestigious properties in every corner of the country. From secluded coastal retreats to vibrant metropolitan suites, our platform maps the pinnacle of local hospitality to a single, seamless interface.",
    button: "Explore Destinations",
    image:
      "https://images.unsplash.com/photo-1507525428034-b723cf961d3e",
    dark: false,
  },
  {
    title: "24/7 Concierge Support",
    description:
      "Our commitment to your experience never sleeps. Benefit from around-the-clock professional support designed to handle every request with urgency and discretion.",
    button: "Contact Concierge",
    image:
      "https://images.unsplash.com/photo-1516321318423-f06f85e504b3",
    dark: true,
  },
  {
    title: "Verified Reviews & Ratings",
    description:
      "Trust is our core currency. Every rating and review on LuxeStay Collective is generated by verified guests who have completed their stays.",
    button: "View Testimonials",
    image:
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267",
    dark: false,
  },
];

const AboutSection = () => {
  return (
    <section className="about-section">
      {/* LEFT SIDE */}
      <div className="left-content">
        <button className="top-btn">About Deluxe Bookings</button>

        <h1>
          Designed for Discerning <br />
          Travellers
        </h1>

        <p>
          Deluxe Bookings bridges the gap between local luxury and global
          standards. We provide a sophisticated ecosystem where booking
          excellence is the baseline, and your peace of mind is our priority.
          Experience hospitality reimagined through intelligent design and
          verified trust.
        </p>

        <div className="gallery">
          <img
            src="https://images.unsplash.com/photo-1505693416388-ac5ce068fe85"
            alt=""
          />

          <img
            src="https://images.unsplash.com/photo-1494526585095-c41746248156"
            alt=""
          />
        </div>
      </div>

      {/* RIGHT SIDE */}
      <div className="right-content">
        {cards.map((card, index) => (
          <div
            className={`info-card ${card.dark ? "dark-card" : ""}`}
            key={index}
          >
            <div className="card-text">
              <h2>{card.title}</h2>

              <p>{card.description}</p>

              <button className="card-btn">
                {card.button}

                <span>↗</span>
              </button>
            </div>

            <div className="card-image">
              <img src={card.image} alt="" />
            </div>
          </div>
        ))}
      </div>
    </section>
  );
};

export default AboutSection;