const southAfricaCatalogSeed = {
  hero: {
    title: 'Luxury Without\nCompromise',
    subtitle:
      "Showcase your property to the world's most discerning travellers. We do not just list hotels; we curate experiences for a global audience that values quality over quantity.",
    ctaLabel: 'Apply to Join',
  },
  navbar: {
    destinationSuggestions: [
      { name: 'Cape Town', region: 'Western Cape, South Africa' },
      { name: 'Johannesburg', region: 'Gauteng, South Africa' },
      { name: 'Durban', region: 'KwaZulu-Natal, South Africa' },
      { name: 'Pretoria', region: 'Gauteng, South Africa' },
      { name: 'Stellenbosch', region: 'Western Cape, South Africa' },
      { name: 'Franschhoek', region: 'Western Cape, South Africa' },
      { name: 'Port Elizabeth', region: 'Eastern Cape, South Africa' },
      { name: 'Knysna', region: 'Garden Route, South Africa' },
      { name: 'George', region: 'Garden Route, South Africa' },
      { name: 'Kruger National Park', region: 'Mpumalanga, South Africa' },
    ],
  },
  search: {
    breadcrumbs: ['Home', 'South Africa', 'Western Cape', 'Cape Town', 'Search results'],
    heading: 'South Africa: 7,703 properties found',
    sortLabel: 'Sort by: Our top picks',
    alertText: '83% of places to stay are unavailable for your dates on our site.',
    map: {
      label: 'Show on map',
      embedUrl: 'https://www.google.com/maps?q=hotels+in+south+africa&output=embed',
      searchUrl: 'https://www.google.com/maps/search/hotels+in+south+africa',
    },
    properties: [
      {
        id: 1,
        title: 'WEX1 2BR Ensuite Apartment with Pool, Gym and Parking',
        area: 'Woodstock, Cape Town',
        distanceLabel: '2.9 km from centre',
        beachLabel: '150 m from beach',
        oldPrice: 'ZAR 1,429',
        price: 'ZAR 1,157',
        reviewScore: 8.2,
        reviewSummary: 'Very good',
        reviewCount: 611,
        valueForMoney: 8.4,
        tag: 'New to Deluxe Bookings',
        dealTag: 'Getaway Deal',
        unitType: 'Two-Bedroom Apartment',
        unitDetails: ['Entire apartment 2 bedrooms 2 bathrooms 1 kitchen 99 m2', '3 beds (2 singles, 1 large double)'],
        freeCancellation: true,
        stars: 5,
      },
      {
        id: 2,
        title: 'The Bantry Bay Penthouse with Atlantic Views',
        area: 'Bantry Bay, Cape Town',
        distanceLabel: '4.1 km from centre',
        beachLabel: '350 m from beach',
        oldPrice: 'ZAR 2,990',
        price: 'ZAR 2,540',
        reviewScore: 9.1,
        reviewSummary: 'Superb',
        reviewCount: 418,
        valueForMoney: 8.7,
        tag: 'Guest favourite',
        dealTag: 'Limited-time Deal',
        unitType: 'Executive Suite',
        unitDetails: ['Private suite 1 bedroom 1 bathroom ocean-facing lounge', '1 extra-large double bed'],
        freeCancellation: true,
        stars: 5,
      },
      {
        id: 3,
        title: 'Umhlanga Dunes Resort Apartment',
        area: 'Umhlanga, Durban',
        distanceLabel: '12 km from centre',
        beachLabel: '80 m from beach',
        oldPrice: 'ZAR 1,860',
        price: 'ZAR 1,420',
        reviewScore: 8.7,
        reviewSummary: 'Fabulous',
        reviewCount: 729,
        valueForMoney: 8.3,
        tag: 'Popular with families',
        dealTag: 'Coastal Deal',
        unitType: 'Sea View Apartment',
        unitDetails: ['Entire apartment 2 bedrooms 2 bathrooms 1 kitchen', '2 double beds and 1 sofa bed'],
        freeCancellation: true,
        stars: 4,
      },
      {
        id: 4,
        title: 'Sandton Skyline Hotel and Residences',
        area: 'Sandton, Johannesburg',
        distanceLabel: '1.4 km from centre',
        beachLabel: 'City stay',
        oldPrice: 'ZAR 1,950',
        price: 'ZAR 1,610',
        reviewScore: 8.4,
        reviewSummary: 'Very good',
        reviewCount: 1332,
        valueForMoney: 8.1,
        tag: 'Business traveller pick',
        dealTag: 'Weekend Value',
        unitType: 'Deluxe Room',
        unitDetails: ['Hotel room 1 bedroom 1 bathroom workspace', '1 king bed'],
        freeCancellation: true,
        stars: 4,
      },
      {
        id: 5,
        title: 'Kruger Riverfront Luxury Lodge',
        area: 'Skukuza, Kruger National Park',
        distanceLabel: '22 km from centre gate',
        beachLabel: 'Riverfront reserve',
        oldPrice: 'ZAR 3,540',
        price: 'ZAR 2,980',
        reviewScore: 9.4,
        reviewSummary: 'Exceptional',
        reviewCount: 204,
        valueForMoney: 8.9,
        tag: 'Safari collection',
        dealTag: 'Early Bird Deal',
        unitType: 'Luxury Chalet',
        unitDetails: ['Private chalet 1 bedroom 1 bathroom outdoor deck', '1 king bed and 1 day bed'],
        freeCancellation: false,
        stars: 5,
      },
      {
        id: 6,
        title: 'Franschhoek Vineyard Manor Suites',
        area: 'Franschhoek, Western Cape',
        distanceLabel: '0.9 km from centre',
        beachLabel: 'Wine valley',
        oldPrice: 'ZAR 2,210',
        price: 'ZAR 1,890',
        reviewScore: 9.0,
        reviewSummary: 'Superb',
        reviewCount: 318,
        valueForMoney: 8.6,
        tag: 'Romantic escapes',
        dealTag: 'Cellar Season Deal',
        unitType: 'Garden Suite',
        unitDetails: ['Suite 1 bedroom 1 bathroom lounge and patio', '1 king bed'],
        freeCancellation: true,
        stars: 5,
      },
      {
        id: 7,
        title: 'The Bay Boardwalk Hotel and Spa',
        area: 'Summerstrand, Gqeberha',
        distanceLabel: '5.2 km from centre',
        beachLabel: '250 m from beach',
        oldPrice: 'ZAR 1,620',
        price: 'ZAR 1,290',
        reviewScore: 8.5,
        reviewSummary: 'Very good',
        reviewCount: 845,
        valueForMoney: 8.2,
        tag: 'Spa and wellness',
        dealTag: 'Seaside Deal',
        unitType: 'Premium Double Room',
        unitDetails: ['Room 1 bedroom 1 bathroom balcony access', '1 queen bed'],
        freeCancellation: true,
        stars: 4,
      },
      {
        id: 8,
        title: 'Knysna Heads Lagoon Villa',
        area: 'Knysna, Garden Route',
        distanceLabel: '3.8 km from centre',
        beachLabel: 'Lagoon access',
        oldPrice: 'ZAR 2,880',
        price: 'ZAR 2,340',
        reviewScore: 9.2,
        reviewSummary: 'Superb',
        reviewCount: 192,
        valueForMoney: 8.8,
        tag: 'Scenic retreat',
        dealTag: 'Garden Route Escape',
        unitType: 'Three-Bedroom Villa',
        unitDetails: ['Entire villa 3 bedrooms 2 bathrooms full kitchen', '4 beds and private deck'],
        freeCancellation: true,
        stars: 5,
      },
      {
        id: 9,
        title: 'Pretoria Jacaranda Boutique Residence',
        area: 'Brooklyn, Pretoria',
        distanceLabel: '2.2 km from centre',
        beachLabel: 'City stay',
        oldPrice: 'ZAR 1,400',
        price: 'ZAR 1,090',
        reviewScore: 8.1,
        reviewSummary: 'Very good',
        reviewCount: 455,
        valueForMoney: 8.0,
        tag: 'Boutique stay',
        dealTag: 'City Saver Deal',
        unitType: 'Superior Room',
        unitDetails: ['Room 1 bedroom 1 bathroom breakfast included', '1 queen bed'],
        freeCancellation: true,
        stars: 4,
      },
      {
        id: 10,
        title: 'Stellenbosch Art House Apartments',
        area: 'Stellenbosch Central, Stellenbosch',
        distanceLabel: '0.6 km from centre',
        beachLabel: 'Winelands',
        oldPrice: 'ZAR 1,730',
        price: 'ZAR 1,360',
        reviewScore: 8.8,
        reviewSummary: 'Fabulous',
        reviewCount: 522,
        valueForMoney: 8.5,
        tag: 'Top-rated hosts',
        dealTag: 'Winelands Value',
        unitType: 'Studio Apartment',
        unitDetails: ['Studio 1 bathroom kitchenette smart TV', '1 double bed'],
        freeCancellation: true,
        stars: 4,
      },
      {
        id: 11,
        title: 'Plettenberg Bay Ocean Edge Suites',
        area: 'Plettenberg Bay, Garden Route',
        distanceLabel: '1.9 km from centre',
        beachLabel: '120 m from beach',
        oldPrice: 'ZAR 2,200',
        price: 'ZAR 1,790',
        reviewScore: 8.9,
        reviewSummary: 'Fabulous',
        reviewCount: 366,
        valueForMoney: 8.4,
        tag: 'Beachfront collection',
        dealTag: 'Ocean Deal',
        unitType: 'Ocean Suite',
        unitDetails: ['Suite 1 bedroom 1 bathroom balcony ocean view', '1 king bed'],
        freeCancellation: true,
        stars: 5,
      },
      {
        id: 12,
        title: 'Camps Bay Crest Designer Apartment',
        area: 'Camps Bay, Cape Town',
        distanceLabel: '5.4 km from centre',
        beachLabel: '450 m from beach',
        oldPrice: 'ZAR 2,640',
        price: 'ZAR 2,090',
        reviewScore: 9.0,
        reviewSummary: 'Superb',
        reviewCount: 287,
        valueForMoney: 8.6,
        tag: 'Premium host',
        dealTag: 'Sunset Deal',
        unitType: 'Designer Apartment',
        unitDetails: ['Entire apartment 2 bedrooms 2 bathrooms sea view', '2 king beds'],
        freeCancellation: true,
        stars: 5,
      },
    ],
  },
  filters: {
    previousFiltersTop: [
      { id: 'guest-houses', label: 'Guest houses', count: 304 },
      { id: 'chalets', label: 'Chalets', count: 8 },
      { id: 'bed-and-breakfast', label: 'Bed and Breakfast', count: 48 },
      { id: 'holiday-homes', label: 'Holiday homes', count: 182 },
      { id: 'homestays', label: 'Homestays', count: 39 },
      { id: 'country-houses', label: 'Country houses', count: 1 },
      { id: 'apartments', label: 'Apartments', count: 2394 },
      { id: 'luxury-tents', label: 'Luxury tents', count: 1 },
    ],
    budget: {
      rangeLabel: 'ZAR 300+ - ZAR 5,000+',
      histogram: [9, 16, 28, 46, 70, 88, 74, 58, 42, 31, 24, 19, 15, 12, 10, 8, 7, 6, 5, 4],
    },
    propertyFilters: [
      { id: 'breakfast-included', label: 'Breakfast included', count: 2788 },
      { id: 'superb-9-legacy', label: 'Superb: 9+ / Exceptional: 10+', count: 1088 },
      { id: 'hotels', label: 'Hotels', count: 237 },
      { id: 'very-good-8-legacy', label: 'Very good: 8+ / Fabulou...', count: 1843 },
      { id: 'waterfront', label: 'Waterfront', count: 49 },
      { id: 'camps-bay', label: 'Camps bay', count: 180 },
      { id: 'parking', label: 'Parking', count: 2859 },
      { id: 'green-point', label: 'Green Point', count: 234 },
    ],
    reviewScore: [
      { id: 'superb-9', label: 'Superb: 9+', count: 1088 },
      { id: 'very-good-8', label: 'Very good: 8+', count: 1843 },
      { id: 'good-7', label: 'Good: 7+', count: 2438 },
      { id: 'pleasant-6', label: 'Pleasant: 6+', count: 2886 },
    ],
    beachAccess: [{ id: 'beach-access', label: 'Beach nearby', count: 272 }],
    previousFiltersBottom: [
      { id: 'entire-homes', label: 'Entire homes and apartments', count: 2783 },
      { id: 'apartments-bottom', label: 'Apartments', count: 2394 },
      { id: 'guest-houses-bottom', label: 'Guest houses', count: 304 },
      { id: 'hotels-bottom', label: 'Hotels', count: 237 },
      { id: 'holiday-homes-bottom', label: 'Holiday homes', count: 182 },
      { id: 'villas-bottom', label: 'Villas', count: 98 },
      { id: 'bed-and-breakfast-bottom', label: 'Bed and Breakfast', count: 48 },
      { id: 'homestays-bottom', label: 'Homestays', count: 39 },
      { id: 'hostels-bottom', label: 'Hostels', count: 22 },
      { id: 'lodges-bottom', label: 'Lodges', count: 18 },
      { id: 'chalets-bottom', label: 'Chalets', count: 8 },
      { id: 'resorts-bottom', label: 'Resorts', count: 2 },
      { id: 'boats-bottom', label: 'Boats', count: 2 },
      { id: 'country-houses-bottom', label: 'Country houses', count: 1 },
      { id: 'luxury-tents-bottom', label: 'Luxury tents', count: 1 },
    ],
    bedroomsBathrooms: {
      bedrooms: 0,
      bathrooms: 0,
    },
    highlyRatedFeatures: [{ id: 'very-good-breakfast', label: 'Very good breakfast', count: 184 }],
    travelGroup: [
      { id: 'pets', label: 'Pets allowed', count: 218 },
      { id: 'adults-only', label: 'Adults only', count: 159 },
      { id: 'large-group', label: 'Travel Proud: LGBTO+ friendly', count: 264 },
    ],
    brands: [
      { id: 'villa-amarina', label: 'Villa Armarina', count: 25 },
      { id: 'totalstay', label: 'Totalstay', count: 14 },
      { id: 'newmark', label: 'Newmark Hotels, Reserves and Lodges', count: 8 },
      { id: 'trevparkworld', label: 'TrevPAR World Group', count: 8 },
      { id: 'protea', label: 'Protea Hotels by Marriott', count: 5 },
      { id: 'southern-sun', label: 'Southern Sun Hotels', count: 5 },
      { id: 'onomo', label: 'ONOMO HOTELS', count: 3 },
      { id: 'marriott', label: 'Marriott Hotels and Resorts', count: 3 },
      { id: 'capital', label: 'The Capital Hotel and Apartments', count: 2 },
      { id: 'first-group', label: 'First Group', count: 2 },
    ],
    funThings: [
      { id: 'beach-fun', label: 'Beach', count: 521 },
      { id: 'golf-fun', label: 'Golf course (within 3 km)', count: 487 },
      { id: 'hiking-fun', label: 'Hiking', count: 434 },
      { id: 'fitness-fun', label: 'Fitness centre', count: 295 },
      { id: 'cycling-fun', label: 'Cycling', count: 276 },
    ],
    certifications: [{ id: 'sustainability', label: 'Sustainability certification', count: 11 }],
    propertyRating: [
      { id: 'star-1', label: '1 star', count: 1 },
      { id: 'star-2', label: '2 stars', count: 52 },
      { id: 'star-3', label: '3 stars', count: 832 },
      { id: 'star-4', label: '4 stars', count: 1427 },
      { id: 'star-5', label: '5 stars', count: 85 },
    ],
  },
  thingsToDo: {
    title: 'Things to do in South Africa',
    cards: [
      { id: 1, title: 'Hotels', dates: '14 Dec - 17 Dec, 2 adults', count: '7,703 available' },
      { id: 2, title: 'Apartments', dates: '14 Dec - 17 Dec, 2 adults', count: '4,281 available' },
      { id: 3, title: 'Resorts', dates: '14 Dec - 17 Dec, 2 adults', count: '413 available' },
      { id: 4, title: 'Villas', dates: '14 Dec - 17 Dec, 2 adults', count: '1,203 available' },
      { id: 5, title: 'Cottages', dates: '14 Dec - 17 Dec, 2 adults', count: '688 available' },
    ],
  },
  footer: {
    heading: 'Engage with Us in Conversation.',
    description:
      "In a global world based on communication, a premium hospitality brand must look beyond its borders, open up to new experiences, and dare to be different. Meeting the brightest minds of one's time is the most effective way to nurture creativity and trust.",
    imageAlt: 'Luxury villa with a pool',
    columns: [
      {
        title: 'About Us',
        items: ['Our Story', 'Vetting Process', 'Sustainability', 'Careers', 'Contact'],
      },
      {
        title: 'Customer Service',
        items: ['Prices and Payments', 'Booking Policy', 'Return and Cancellation', 'Terms of Service', 'Privacy Policy'],
      },
      {
        title: 'Social Media',
        items: ['Instagram', 'Facebook', 'LinkedIn', 'X (Twitter)'],
      },
    ],
  },
}

module.exports = southAfricaCatalogSeed
